<?php
/**
 * GroupFitnessClassTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iBooking\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iBookings API - Final
 *
 * iBooking components
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iBooking\Client;

/**
 * GroupFitnessClassTest Class Doc Comment
 *
 * @category    Class
 * @description GroupFitnessClass
 * @package     iBooking\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GroupFitnessClassTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GroupFitnessClass"
     */
    public function testGroupFitnessClass()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "studio"
     */
    public function testPropertyStudio()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "available"
     */
    public function testPropertyAvailable()
    {
    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "instructors"
     */
    public function testPropertyInstructors()
    {
    }

    /**
     * Test attribute "room"
     */
    public function testPropertyRoom()
    {
    }

    /**
     * Test attribute "video"
     */
    public function testPropertyVideo()
    {
    }

    /**
     * Test attribute "bookable"
     */
    public function testPropertyBookable()
    {
    }

    /**
     * Test attribute "booking_opens_at"
     */
    public function testPropertyBookingOpensAt()
    {
    }

    /**
     * Test attribute "user_status"
     */
    public function testPropertyUserStatus()
    {
    }

    /**
     * Test attribute "waitlist"
     */
    public function testPropertyWaitlist()
    {
    }

    /**
     * Test attribute "cancellation_penalty"
     */
    public function testPropertyCancellationPenalty()
    {
    }

    /**
     * Test attribute "cancel_text"
     */
    public function testPropertyCancelText()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }
}
