<?php
/**
 * EventApiTest
 * PHP version 5
 *
 * @category Class
 * @package  iBooking\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iBookings API - Final
 *
 * iBooking components
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace iBooking\Client;

use iBooking\Client\Configuration;
use iBooking\Client\ApiException;
use iBooking\Client\ObjectSerializer;

/**
 * EventApiTest Class Doc Comment
 *
 * @category Class
 * @package  iBooking\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for bookEvent
     *
     * Book an event.
     *
     */
    public function testBookEvent()
    {
    }

    /**
     * Test case for cancelEvent
     *
     * Cancel an event booking.
     *
     */
    public function testCancelEvent()
    {
    }

    /**
     * Test case for getEventStudios
     *
     * Return studios with events and their event categories.
     *
     */
    public function testGetEventStudios()
    {
    }

    /**
     * Test case for getEvents
     *
     * Get events.
     *
     */
    public function testGetEvents()
    {
    }

    /**
     * Test case for getUserEventBookings
     *
     * Return all event bookings of a user.
     *
     */
    public function testGetUserEventBookings()
    {
    }
}
