<?php
/**
 * ScheduleApiTest
 * PHP version 5
 *
 * @category Class
 * @package  iBooking\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * iBookings API - Final
 *
 * iBooking components
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace iBooking\Client;

use iBooking\Client\Configuration;
use iBooking\Client\ApiException;
use iBooking\Client\ObjectSerializer;

/**
 * ScheduleApiTest Class Doc Comment
 *
 * @category Class
 * @package  iBooking\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScheduleApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getBasicInfo
     *
     * This method returns basic information, and optionally also the output of the getStudios and getInstructors methods..
     *
     */
    public function testGetBasicInfo()
    {
    }

    /**
     * Test case for getScheduleStudios
     *
     * This method returns a full list of all studios that belongs to the parent entity..
     *
     */
    public function testGetScheduleStudios()
    {
    }

    /**
     * Test case for scheduleAddBookingPost
     *
     * This method adds a booking to the provided class for the provided user (via token)..
     *
     */
    public function testScheduleAddBookingPost()
    {
    }

    /**
     * Test case for scheduleCancelBookingPost
     *
     * This method cancels/deletes a booking from the provided class for the provided user (via token)..
     *
     */
    public function testScheduleCancelBookingPost()
    {
    }

    /**
     * Test case for scheduleGetClassGet
     *
     * Will return all information related to a group class, including descriptions and/or images of the class/instructors..
     *
     */
    public function testScheduleGetClassGet()
    {
    }

    /**
     * Test case for scheduleGetInstructorsGet
     *
     * This method returns a full list of all group class instructors..
     *
     */
    public function testScheduleGetInstructorsGet()
    {
    }

    /**
     * Test case for scheduleGetScheduleGet
     *
     * Will return the group class schedule. All parameters are GET parameters..
     *
     */
    public function testScheduleGetScheduleGet()
    {
    }
}
